<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        // Ошибка в setTimeout
        // Что вы думаете? Выполнится ли .catch? Поясните свой ответ.

        new Promise(function (resolve, reject) {
            setTimeout(() => {
                throw new Error("Whoops!");
            }, 1000);
        }).catch(alert);

        // Ответ: нет, не выполнится:
        // Как было сказано в главе, здесь присутствует "скрытый try..catch" вокруг кода функции.
        //  Поэтому обрабатываются все синхронные ошибки.
        //  В данном примере ошибка генерируется не по ходу выполнения кода, а позже.
        //  Поэтому промис не может обработать её.
    </script>
</body>

</html>